harmless = [
    "Never have I ever sung in the shower.",
    "Never have I ever eaten a whole pizza by myself.",
    "Never have I ever gone on a picnic.",
    "Never have I ever had a pet.",
    "Never have I ever danced in public.",
    "Never have I ever ridden a roller coaster.",
    "Never have I ever baked cookies from scratch.",
    "Never have I ever played a board game.",
    "Never have I ever tried a food from a different culture.",
    "Never have I ever gone camping.",
    "Never have I ever taken a selfie.",
    "Never have I ever read a Harry Potter book.",
    "Never have I ever been to a music concert.",
    "Never have I ever learned to swim.",
    "Never have I ever written a love letter.",
    "Never have I ever gone fishing.",
    "Never have I ever ridden a horse.",
    "Never have I ever watched a sunrise.",
    "Never have I ever planted a tree.",
    "Never have I ever gone ice skating.",
    "Never have I ever built a sandcastle.",
    "Never have I ever flown a kite.",
    "Never have I ever owned a bicycle.",
    "Never have I ever had a pen pal.",
    "Never have I ever visited a zoo.",
    "Never have I ever gone on a road trip.",
    "Never have I ever baked a cake.",
    "Never have I ever climbed a tree.",
    "Never have I ever played hide and seek.",
    "Never have I ever sung karaoke.",
    "Never have I ever had a lemonade stand.",
    "Never have I ever played a musical instrument.",
    "Never have I ever gone on a hot air balloon ride.",
    "Never have I ever seen a shooting star.",
    "Never have I ever worn mismatched socks.",
    "Never have I ever ridden a Ferris wheel.",
    "Never have I ever made a snowman.",
    "Never have I ever watched a meteor shower.",
    "Never have I ever gone roller skating.",
    "Never have I ever built a snow fort.",
    "Never have I ever had a pillow fight.",
    "Never have I ever written a poem.",
    "Never have I ever gone on a scavenger hunt.",
    "Never have I ever taken a cooking class.",
    "Never have I ever made a paper airplane.",
    "Never have I ever danced in the rain.",
    "Never have I ever played mini golf.",
    "Never have I ever gone horseback riding on a beach.",
    "Never have I ever tried a new cuisine while traveling.",
    "Never have I ever watched a full season of a TV show in one day.",
    "Never have I ever picked fruit from a tree and eaten it.",
    "Never have I ever sung in a choir or musical group.",
    "Never have I ever done a handstand.",
    "Never have I ever played in the rain.",
    "Never have I ever built a sandcastle on the beach.",
    "Never have I ever tried sushi.",
    "Never have I ever been to a theme park.",
    "Never have I ever baked my own bread.",
    "Never have I ever gone on a hike in the mountains.",
    "Never have I ever flown a kite on a windy day.",
    "Never have I ever gone on a spontaneous road trip.",
    "Never have I ever had a snowball fight.",
    "Never have I ever played Frisbee.",
    "Never have I ever planted flowers in a garden.",
    "Never have I ever watched a documentary about space.",
    "Never have I ever painted a picture.",
    "Never have I ever been on a camping trip with friends.",
    "Never have I ever made a homemade pizza.",
    "Never have I ever learned a dance routine.",
    "Never have I ever done a cartwheel.",
    "Never have I ever taken a bubble bath.",
    "Never have I ever gone to a costume party.",
    "Never have I ever tried a new ice cream flavor.",
    "Never have I ever flown a remote-controlled drone.",
    "Never have I ever written a letter to Santa Claus.",
    "Never have I ever sung in a karaoke competition.",
    "Never have I ever participated in a talent show.",
    "Never have I ever ridden a Ferris wheel at night.",
    "Never have I ever done a puzzle with over 500 pieces.",
    "Never have I ever gone to a drive-in movie theater.",
    "Never have I ever played miniature golf.",
    "Never have I ever been to a science museum.",
    "Never have I ever tried virtual reality gaming.",
    "Never have I ever gone on a boat ride.",
    "Never have I ever built a snow fort with friends.",
    "Never have I ever gone on a picnic in the park.",
    "Never have I ever had a water balloon fight.",
    "Never have I ever made homemade lemonade.",
    "Never have I ever tried a food challenge.",
    "Never have I ever gone on a family vacation.",
    "Never have I ever attended a school dance.",
    "Never have I ever gone on a rollercoaster more than once in a row.",
    "Never have I ever gone to a summer camp.",
    "Never have I ever participated in a charity run.",
    "Never have I ever had a snow day from school.",
    "Never have I ever built a treehouse.",
    "Never have I ever played in a sandbox.",
    "Never have I ever gone to a trampoline park.",
    "Never have I ever worn pajamas all day.",
    "Never have I ever gone on a family road trip.",
    "Never have I ever gone on a hot air balloon ride.",
    "Never have I ever seen a meteor shower.",
    "Never have I ever tried a food from a street vendor.",
    "Never have I ever gone on a midnight bike ride.",
    "Never have I ever built a snowman taller than myself.",
    "Never have I ever watched a full season of a reality TV show.",
    "Never have I ever ridden a mechanical bull.",
    "Never have I ever attended a surprise party.",
    "Never have I ever taken a yoga class.",
    "Never have I ever ridden a horse on the beach.",
    "Never have I ever tried bungee jumping.",
    "Never have I ever gone on a river rafting adventure.",
    "Never have I ever participated in a charity fundraiser.",
    "Never have I ever taken a cooking class.",
    "Never have I ever gone on a blind date.",
    "Never have I ever had a picnic in a botanical garden.",
    "Never have I ever ridden a zip line.",
    "Never have I ever been to a cultural festival.",
    "Never have I ever tried a food challenge.",
    "Never have I ever swum with dolphins.",
    "Never have I ever attended a costume party.",
    "Never have I ever gone on a spontaneous road trip with friends.",
    "Never have I ever learned a new language.",
    "Never have I ever played a practical joke on someone.",
    "Never have I ever gone on a weekend getaway with friends.",
    "Never have I ever ridden a tandem bicycle.",
    "Never have I ever had a movie marathon.",
    "Never have I ever ridden a roller coaster in the front row.",
    "Never have I ever gone ice skating on a frozen pond.",
    "Never have I ever built a sandcastle with intricate details.",
    "Never have I ever tried paddleboarding.",
    "Never have I ever gone on a hot air balloon ride at sunrise.",
    "Never have I ever had a snowball fight with strangers.",
    "Never have I ever tried a food I couldn't pronounce.",
    "Never have I ever participated in a flash mob.",
    "Never have I ever ridden a motorcycle.",
    "Never have I ever gone on a scenic helicopter tour.",
    "Never have I ever tried indoor skydiving.",
    "Never have I ever attended a masquerade ball.",
    "Never have I ever gone on a sailing trip.",
    "Never have I ever been on a safari.",
    "Never have I ever tried a food that was too spicy for me.",
    "Never have I ever gone on a camping trip with friends.",
    "Never have I ever ridden a roller coaster backward.",
    "Never have I ever participated in a 5K race.",
    "Never have I ever tried a food that made me cry.",
    "Never have I ever gone on a cross-country road trip.",
    "Never have I ever ridden a skateboard.",
    "Never have I ever tried a food from a different continent.",
    "Never have I ever gone on a hot air balloon ride at sunset.",
    "Never have I ever stargazed for hours on a clear night.",
    "Never have I ever built a sandcastle that was taller than me.",
    "Never have I ever volunteered for a charity event.",
    "Never have I ever taken a scenic train ride.",
    "Never have I ever made homemade jam or preserves.",
    "Never have I ever gone on a spontaneous road trip with no destination in mind.",
    "Never have I ever gone snorkeling in a coral reef.",
    "Never have I ever written a heartfelt letter to a loved one.",
    "Never have I ever participated in a community clean-up event.",
    "Never have I ever grown my own vegetables in a garden.",
    "Never have I ever gone on a whale-watching tour.",
    "Never have I ever taken a pottery class.",
    "Never have I ever attended a wildlife safari.",
    "Never have I ever baked a cake from scratch for a special occasion.",
    "Never have I ever learned a traditional dance.",
    "Never have I ever taken a scenic hike in a national park.",
    "Never have I ever gone on a solo backpacking trip.",
    "Never have I ever written a song or composed music.",
    "Never have I ever participated in a book club.",
    "Never have I ever tried a food challenge and succeeded.",
    "Never have I ever made a scrapbook of memorable moments.",
    "Never have I ever painted a mural on a wall.",
    "Never have I ever taken a midnight swim in the ocean.",
    "Never have I ever gone ziplining through a rainforest.",
    "Never have I ever made homemade ice cream.",
    "Never have I ever learned to juggle.",
    "Never have I ever participated in a charity run for a good cause.",
    "Never have I ever gone on a camping trip in the wilderness.",
    "Never have I ever learned a traditional craft or art form.",
    "Never have I ever visited an art museum and appreciated the exhibits.",
    "Never have I ever taken a pottery class and created pottery.",
    "Never have I ever attended a cultural festival in a foreign country.",
    "Never have I ever tried a food that I couldn't identify by its appearance.",
    "Never have I ever gone on a road trip with friends and stayed in motels along the way.",
    "Never have I ever made a homemade gift for someone special.",
    "Never have I ever taken a scenic bike ride through the countryside.",
    "Never have I ever learned to play a musical instrument.",
    "Never have I ever participated in a science experiment or conducted one myself.",
    "Never have I ever gone on a hot air balloon ride with friends.",
    "Never have I ever planted a tree in my backyard.",
    "Never have I ever gone on a wine tasting tour.",
    "Never have I ever tried my hand at making pottery on a pottery wheel.",
    "Never have I ever built a treehouse with my friends.",
    "Never have I ever attended a traditional tea ceremony.",
    "Never have I ever gone on a cruise to an exotic destination.",
    "Never have I ever taken a spontaneous trip to a foreign country.",
    "Never have I ever tried a food that I couldn't pronounce."
]


delicate = [
    "Never have I ever cried during a movie.",
    "Never have I ever kept a diary.",
    "Never have I ever lied to protect someone's feelings.",
    "Never have I ever had a secret crush.",
    "Never have I ever been in love.",
    "Never have I ever had a one-night stand.",
    "Never have I ever been ghosted in a relationship.",
    "Never have I ever had a long-distance relationship.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever sent a risky text.",
    "Never have I ever cheated on a test.",
    "Never have I ever lied about my age.",
    "Never have I ever pretended to be someone else online.",
    "Never have I ever faked being sick to skip school or work.",
    "Never have I ever regretted breaking up with someone.",
    "Never have I ever lied about my relationship status.",
    "Never have I ever snooped through someone's phone.",
    "Never have I ever had a crush on a coworker.",
    "Never have I ever had a crush on a teacher.",
    "Never have I ever kissed someone on the first date.",
    "Never have I ever been on a blind date.",
    "Never have I ever used a dating app.",
    "Never have I ever gone skinny dipping.",
    "Never have I ever had a crush on a friend's sibling.",
    "Never have I ever had a crush on a friend's partner.",
    "Never have I ever had a romantic dream about someone.",
    "Never have I ever written a love poem.",
    "Never have I ever written a love song.",
    "Never have I ever been stood up on a date.",
    "Never have I ever had a crush on a celebrity.",
    "Never have I ever had a romantic getaway.",
    "Never have I ever had a rebound relationship.",
    "Never have I ever confessed my feelings to a crush.",
    "Never have I ever been in a love triangle.",
    "Never have I ever dated someone significantly older or younger.",
    "Never have I ever had a crush on a fictional character.",
    "Never have I ever been serenaded or serenaded someone.",
    "Never have I ever dated someone my friends didn't approve of.",
    "Never have I ever cried over a breakup.",
    "Never have I ever had a secret admirer.",
    "Never have I ever fallen in love at first sight.",
    "Never have I ever written a love letter that I never sent.",
    "Never have I ever had a crush on a boss or supervisor.",
    "Never have I ever rekindled a past romance.",
    "Never have I ever been caught snooping through someone's belongings.",
    "Never have I ever had a crush on a neighbor.",
    "Never have I ever fantasized about being in a romance novel.",
    "Never have I ever been in a long-distance relationship that failed.",
    "Never have I ever dated someone my friends disliked.",
    "Never have I ever had a crush on a close friend's sibling.",
    "Never have I ever had a secret crush on a coworker.",
    "Never have I ever kissed someone and immediately regretted it.",
    "Never have I ever had my heart broken.",
    "Never have I ever been in a relationship where I felt used.",
    "Never have I ever had a crush on someone who was already in a relationship.",
    "Never have I ever lied about my relationship status to someone I was interested in.",
    "Never have I ever been in a relationship where I felt manipulated.",
    "Never have I ever sent a flirty text to the wrong person.",
    "Never have I ever had an embarrassing romantic mishap.",
    "Never have I ever been caught stalking someone on social media.",
    "Never have I ever been in a love triangle.",
    "Never have I ever had a major fight with a significant other in public.",
    "Never have I ever been on a date that was a complete disaster.",
    "Never have I ever had a crush on a teacher or professor.",
    "Never have I ever had a friend try to set me up on a date.",
    "Never have I ever been friend-zoned by someone I liked.",
    "Never have I ever had a crush on someone because of their accent.",
    "Never have I ever gone on a date and pretended to like the same things as the other person.",
    "Never have I ever fallen for a pickup line.",
    "Never have I ever had a romantic encounter in a public place.",
    "Never have I ever had a relationship that I kept secret from my friends.",
    "Never have I ever rekindled a past romance and regretted it.",
    "Never have I ever had a crush on a fictional character.",
    "Never have I ever been in a relationship with someone significantly older or younger.",
    "Never have I ever had a crush on a boss or supervisor.",
    "Never have I ever dated someone solely for their looks.",
    "Never have I ever been in a relationship where I felt smothered.",
    "Never have I ever had a crush on a neighbor.",
    "Never have I ever had a crush on someone because of their job.",
    "Never have I ever gone on a date with someone I met online and immediately regretted it.",
    "Never have I ever had a crush on someone because of their social media posts.",
    "Never have I ever been in a relationship that my family disapproved of.",
    "Never have I ever had a crush on someone because of their voice.",
    "Never have I ever been in a relationship where I was the one who got dumped.",
    "Never have I ever been on a date with someone who didn't look like their profile picture.",
    "Never have I ever had a crush on someone because of their style or fashion sense.",
    "Never have I ever dated someone I met at a bar.",
    "Never have I ever had a crush on someone because of their sense of humor.",
    "Never have I ever been in a relationship where I felt ignored.",
    "Never have I ever had a crush on someone because of their intelligence.",
    "Never have I ever dated someone I met at a wedding.",
    "Never have I ever had a crush on someone because of their smile.",
    "Never have I ever been in a relationship where I was the one who cheated.",
    "Never have I ever had a crush on a best friend's sibling.",
    "Never have I ever had a rebound relationship.",
    "Never have I ever kept a love letter from an ex.",
    "Never have I ever had a secret admirer.",
    "Never have I ever had a crush on someone I met online.",
    "Never have I ever dated someone just to make someone else jealous.",
    "Never have I ever had a relationship with a significant age difference.",
    "Never have I ever been in a love triangle and caused drama.",
    "Never have I ever broken up with someone on a special occasion.",
    "Never have I ever had a crush on a coworker and acted on it.",
    "Never have I ever gone on a date to a location I knew my ex would be at.",
    "Never have I ever dated someone who was already in a committed relationship.",
    "Never have I ever pretended to like someone to get closer to their friend.",
    "Never have I ever rekindled a past romance out of loneliness.",
    "Never have I ever kissed someone I just met at a party.",
    "Never have I ever had a crush on someone because of their social media posts.",
    "Never have I ever been in a relationship solely for the physical aspect.",
    "Never have I ever lied about my age to seem more mature.",
    "Never have I ever flirted with someone just for the thrill of it.",
    "Never have I ever gone on a date with someone solely for a free meal.",
    "Never have I ever dated someone solely because they were wealthy.",
    "Never have I ever had a crush on a friend's parent.",
    "Never have I ever had a secret online relationship.",
    "Never have I ever had a romantic fantasy about a celebrity.",
    "Never have I ever dated someone just because they were good-looking.",
    "Never have I ever had a crush on a friend's significant other.",
    "Never have I ever gone on a date with someone I met at a bar just for fun.",
    "Never have I ever had a crush on a friend's ex.",
    "Never have I ever dated someone solely because of their job or status.",
    "Never have I ever had a crush on someone who turned out to be completely different in person.",
    "Never have I ever flirted with someone to get something I wanted.",
    "Never have I ever had a romantic encounter with a stranger.",
    "Never have I ever had a crush on someone because of their accent.",
    "Never have I ever dated someone because they reminded me of an ex.",
    "Never have I ever kept a relationship a secret from my closest friends.",
    "Never have I ever been in a relationship where I felt trapped.",
    "Never have I ever had a crush on someone just because of their looks.",
    "Never have I ever ghosted someone I was dating.",
    "Never have I ever gone on a date with someone I had no intention of seeing again.",
    "Never have I ever had a crush on someone purely based on their style or fashion sense.",
    "Never have I ever flirted with someone while in a committed relationship.",
    "Never have I ever had a crush on someone because of their sense of humor.",
    "Never have I ever been in a relationship solely because I didn't want to be alone.",
    "Never have I ever dated someone I met at a wedding just for the experience.",
    "Never have I ever had a crush on a close friend's ex-partner.",
    "Never have I ever had a long-distance relationship that ended amicably.",
    "Never have I ever regretted not expressing my feelings to someone I liked.",
    "Never have I ever fallen in love at first sight and acted on it.",
    "Never have I ever received an anonymous love letter.",
    "Never have I ever written poetry for someone I had feelings for.",
    "Never have I ever gone on a date with someone I met on a dating app.",
    "Never have I ever dated someone significantly younger than me.",
    "Never have I ever dated someone significantly older than me.",
    "Never have I ever rekindled a past romance and felt content about it.",
    "Never have I ever secretly admired someone from afar without them knowing.",
    "Never have I ever had a romantic encounter on a beach at sunset.",
    "Never have I ever had a crush on a celebrity and fantasized about meeting them.",
    "Never have I ever been in a relationship where I felt like I was the one who cared more.",
    "Never have I ever had a crush on a teacher or professor in college.",
    "Never have I ever written love letters back and forth with someone.",
    "Never have I ever gone on a date to a fancy restaurant and dressed up for it.",
    "Never have I ever had a crush on someone because of their intelligence.",
    "Never have I ever had a secret online romance that lasted for months.",
    "Never have I ever dated someone who lived in a different country.",
    "Never have I ever had a romantic encounter under the stars.",
    "Never have I ever had a crush on a friend's sibling and pursued it.",
    "Never have I ever gone on a date with someone I met through mutual friends.",
    "Never have I ever had a crush on someone because of their sense of humor.",
    "Never have I ever had a secret crush on a colleague at work.",
    "Never have I ever gone on a spontaneous road trip with a romantic partner.",
    "Never have I ever had a crush on someone purely because of their accent.",
    "Never have I ever been on a romantic getaway to a tropical island.",
    "Never have I ever written love notes and hidden them in unexpected places for my partner to find.",
    "Never have I ever had a crush on someone because of their kindness and compassion.",
    "Never have I ever had a romantic date on a rooftop with a view.",
    "Never have I ever dated someone who was a complete opposite of my usual type.",
    "Never have I ever had a crush on someone because of their artistic talents.",
    "Never have I ever had a romantic encounter in a picturesque garden.",
    "Never have I ever had a secret crush on a neighbor and never acted on it.",
    "Never have I ever been in a relationship where I was surprised by a heartfelt gesture.",
    "Never have I ever had a crush on someone because of their unique fashion style.",
    "Never have I ever dated someone because of their love for adventure and spontaneity.",
    "Never have I ever had a romantic encounter during a thunderstorm.",
    "Never have I ever had a crush on someone because of their love for animals.",
    "Never have I ever secretly admired someone's dedication and work ethic from afar.",
    "Never have I ever dated someone because of their strong moral values.",
    "Never have I ever had a romantic date at a cozy cabin in the woods.",
    "Never have I ever had a crush on someone because of their culinary skills.",
    "Never have I ever been in a relationship where I felt like I was the one who initiated everything."
]

offensive = [
    "Never have I ever cheated on a significant other.",
    "Never have I ever stolen something significant.",
    "Never have I ever lied on a job application.",
    "Never have I ever driven under the influence.",
    "Never have I ever vandalized property.",
    "Never have I ever been involved in a physical fight.",
    "Never have I ever betrayed a close friend.",
    "Never have I ever spread a malicious rumor.",
    "Never have I ever engaged in illegal activities.",
    "Never have I ever intentionally hurt someone emotionally.",
    "Never have I ever cheated on a test and got caught.",
    "Never have I ever stolen from a family member.",
    "Never have I ever lied to the police.",
    "Never have I ever driven without a valid license.",
    "Never have I ever participated in a hit-and-run accident.",
    "Never have I ever been involved in a public scandal.",
    "Never have I ever cheated on multiple partners.",
    "Never have I ever lied in court or during a legal proceeding.",
    "Never have I ever blackmailed someone.",
    "Never have I ever threatened physical harm to someone.",
    "Never have I ever intentionally ruined someone's reputation.",
    "Never have I ever betrayed a business partner.",
    "Never have I ever engaged in credit card fraud.",
    "Never have I ever been involved in a physical altercation with a family member.",
    "Never have I ever intentionally caused harm to an animal.",
    "Never have I ever sabotaged someone's career.",
    "Never have I ever knowingly spread false information about someone.",
    "Never have I ever participated in a hate crime.",
    "Never have I ever been involved in a serious public altercation.",
    "Never have I ever harassed someone online or in person.",
    "Never have I ever participated in a racially motivated incident.",
    "Never have I ever intentionally damaged someone's property.",
    "Never have I ever threatened someone with a weapon.",
    "Never have I ever participated in cyberbullying.",
    "Never have I ever committed a hate crime.",
    "Never have I ever intentionally ruined someone's business.",
    "Never have I ever engaged in corporate fraud.",
    "Never have I ever stolen from a charity or nonprofit organization.",
    "Never have I ever intentionally harmed a child.",
    "Never have I ever engaged in online harassment.",
    "Never have I ever knowingly spread a false accusation of a crime.",
    "Never have I ever participated in a violent riot.",
    "Never have I ever intentionally damaged a place of worship.",
    "Never have I ever engaged in human trafficking.",
    "Never have I ever threatened to harm someone's family.",
    "Never have I ever participated in a terrorist act.",
    "Never have I ever caused physical harm to someone intentionally.",
    "Never have I ever knowingly spread false accusations about someone.",
    "Never have I ever been involved in a physical assault.",
    "Never have I ever intentionally damaged someone's property out of anger.",
    "Never have I ever threatened someone with a deadly weapon.",
    "Never have I ever participated in a violent hate crime.",
    "Never have I ever engaged in harassment or stalking.",
    "Never have I ever committed a hate crime against someone based on their identity.",
    "Never have I ever engaged in human trafficking.",
    "Never have I ever participated in a terrorist act.",
    "Never have I ever been involved in a hate group.",
    "Never have I ever intentionally caused harm to a child.",
    "Never have I ever vandalized a place of worship.",
    "Never have I ever been involved in a racially motivated assault.",
    "Never have I ever intentionally damaged a place of cultural significance.",
    "Never have I ever threatened someone with harm to their family.",
    "Never have I ever been involved in a violent protest.",
    "Never have I ever engaged in cyberbullying with malicious intent.",
    "Never have I ever committed identity theft.",
    "Never have I ever engaged in organized crime.",
    "Never have I ever participated in a violent riot against law enforcement.",
    "Never have I ever threatened someone with harm to their loved ones.",
    "Never have I ever been involved in a sexual assault.",
    "Never have I ever intentionally damaged a place of education.",
    "Never have I ever participated in a mass shooting.",
    "Never have I ever threatened to harm someone's children.",
    "Never have I ever been involved in a racially motivated attack on an individual.",
    "Never have I ever intentionally caused harm to a vulnerable person.",
    "Never have I ever engaged in human rights violations.",
    "Never have I ever participated in a hate crime against a religious group.",
    "Never have I ever threatened to harm someone's pets.",
    "Never have I ever been involved in a violent attack on a person based on their gender.",
    "Never have I ever intentionally caused harm to a person with disabilities.",
    "Never have I ever engaged in violent extremism.",
    "Never have I ever committed arson with malicious intent.",
    "Never have I ever threatened someone's life with serious harm.",
    "Never have I ever been involved in a violent attack on an LGBTQ+ individual.",
    "Never have I ever intentionally caused harm to an elderly person.",
    "Never have I ever participated in a hate crime against a specific nationality.",
    "Never have I ever threatened someone's life with intent to cause fear.",
    "Never have I ever engaged in violence against a specific religious community.",
    "Never have I ever committed a heinous crime with intent to cause harm to society.",
    "Never have I ever threatened someone's life with intent to cause long-lasting trauma.",
    "Never have I ever been involved in a physical altercation that caused serious harm.",
    "Never have I ever intentionally caused harm to a vulnerable person.",
    "Never have I ever engaged in a hate crime with others.",
    "Never have I ever knowingly spread false accusations that ruined someone's life.",
    "Never have I ever been part of a violent mob that caused destruction.",
    "Never have I ever participated in a kidnapping.",
    "Never have I ever engaged in human trafficking with malicious intent.",
    "Never have I ever been involved in a terrorist attack with casualties.",
    "Never have I ever intentionally caused harm to someone's family.",
    "Never have I ever threatened someone with intent to carry out a violent act.",
    "Never have I ever committed identity theft with malicious intent.",
    "Never have I ever engaged in organized crime that resulted in harm to others.",
    "Never have I ever participated in a violent protest with the intent to harm others.",
    "Never have I ever been involved in a violent hate crime against a specific group.",
    "Never have I ever threatened to harm someone's pets with malicious intent.",
    "Never have I ever participated in a mass shooting with intent to cause harm.",
    "Never have I ever been part of a hate group with a history of violence.",
    "Never have I ever intentionally caused harm to someone's children.",
    "Never have I ever vandalized a place of worship with malicious intent.",
    "Never have I ever been involved in a racially motivated assault with others.",
    "Never have I ever threatened someone's life with intent to cause long-lasting trauma.",
    "Never have I ever been part of a violent attack on an individual based on their identity.",
    "Never have I ever intentionally caused harm to an elderly person.",
    "Never have I ever participated in a hate crime against a specific nationality with others.",
    "Never have I ever threatened someone's life with intent to cause fear.",
    "Never have I ever been involved in violence against a religious community with malicious intent.",
    "Never have I ever committed a heinous crime with intent to cause harm to society.",
    "Never have I ever threatened someone's life with the intent to carry out the threat.",
    "Never have I ever engaged in violence against an LGBTQ+ individual with malicious intent.",
    "Never have I ever intentionally caused harm to a person with disabilities.",
    "Never have I ever participated in violent extremism with others.",
    "Never have I ever committed arson with the intent to harm others.",
    "Never have I ever threatened someone's life with the intent to cause serious harm.",
    "Never have I ever been part of a violent attack on an LGBTQ+ individual with others.",
    "Never have I ever intentionally caused harm to a vulnerable person with malicious intent.",
    "Never have I ever participated in a hate crime against a religious group with others.",
    "Never have I ever threatened someone's life with the intent to cause long-term suffering.",
    "Never have I ever intentionally caused harm to someone's family with malicious intent.",
    "Never have I ever engaged in a physical assault with others.",
    "Never have I ever knowingly spread false accusations that resulted in tragedy.",
    "Never have I ever participated in a violent mob that caused loss of life.",
    "Never have I ever been involved in a kidnapping with harmful intent.",
    "Never have I ever engaged in human trafficking with the intention to harm.",
    "Never have I ever been part of a terrorist attack with catastrophic consequences.",
    "Never have I ever intentionally caused harm to someone's children with malicious intent.",
    "Never have I ever threatened someone's life with the intent to carry out a heinous act.",
    "Never have I ever committed identity theft with the intention of causing harm to others.",
    "Never have I ever engaged in organized crime with harmful intent to society.",
    "Never have I ever participated in a violent protest that resulted in severe injuries.",
    "Never have I ever been involved in a hate crime with others that led to harm.",
    "Never have I ever threatened to harm someone's pets with the intent to cause suffering.",
    "Never have I ever participated in a mass shooting with the intention of causing harm.",
    "Never have I ever been part of a hate group that promoted violence against others.",
    "Never have I ever intentionally caused harm to an elderly person with malicious intent.",
    "Never have I ever vandalized a place of worship with harmful intent.",
    "Never have I ever been involved in a racially motivated assault with others that caused injury.",
    "Never have I ever threatened someone's life with the intent to cause long-lasting trauma.",
    "Never have I ever been part of a violent attack on an individual based on their identity with others.",
    "Never have I ever intentionally caused harm to a vulnerable person with harmful intent.",
    "Never have I ever participated in a hate crime against a specific nationality with others.",
    "Never have I ever threatened someone's life with the intent to cause fear and suffering.",
    "Never have I ever been involved in violence against a religious community with malicious intent.",
    "Never have I ever committed a heinous crime with the intention of causing harm to society.",
    "Never have I ever threatened someone's life with the intent to carry out a devastating act.",
    "Never have I ever engaged in violence against an LGBTQ+ individual with malicious intent.",
    "Never have I ever intentionally caused harm to a person with disabilities with malicious intent.",
    "Never have I ever participated in violent extremism with the intention of causing harm.",
    "Never have I ever committed arson with the intent to cause harm to others.",
    "Never have I ever threatened someone's life with the intent to cause serious harm and suffering.",
    "Never have I ever been part of a violent attack on an LGBTQ+ individual with others.",
    "Never have I ever intentionally caused harm to a vulnerable person with malicious intent for personal gain.",
    "Never have I ever participated in a hate crime against a religious group with others that caused harm.",
    "Never have I ever threatened someone's life with the intent to cause long-term suffering and trauma."
]
